export const cards = [
    { id: 1, card: 'A', naipe: 'copas', icon: 'cards-heart', image: '../assets/copas-a.jpg', title: 'Todos bebem', rule: 'Começam ao mesmo tempo mas o da direita só pode parar de beber quando o da esquerda parar.' },
    { id: 2, card: '2', naipe: 'copas', icon: 'cards-heart', image: '../assets/copas-2.jpg', title: 'Você bebe', rule: 'Beba 2 goles.' },
    { id: 3, card: '3', naipe: 'copas', icon: 'cards-heart', image: '../assets/copas-3.jpg', title: 'Escolha quem vai beber', rule: 'Distribua 3 goles da forma que quiser.' },
    { id: 4, card: '4', naipe: 'copas', icon: 'cards-heart', image: '../assets/copas-4.jpg', title: 'Mão na mesa', rule: 'O último a colocar a mão na mesa bebe.' },
    { id: 5, card: '5', naipe: 'copas', icon: 'cards-heart', image: '../assets/copas-5.jpg', title: 'Mão pro alto', rule: 'O último a colocar a mão para o alto bebe.' },
    { id: 6, card: '6', naipe: 'copas', icon: 'cards-heart', image: '../assets/copas-6.jpg', title: 'Homens bebem', rule: 'Todos os homens bebem.' },
    { id: 7, card: '7', naipe: 'copas', icon: 'cards-heart', image: '../assets/copas-7.jpg', title: 'Mulheres bebem', rule: 'Todos as mulheres bebem.' },
    { id: 8, card: '8', naipe: 'copas', icon: 'cards-heart', image: '../assets/copas-8.jpg', title: 'Na frente', rule: 'Quem está na sua frente bebe um gole.' },
    { id: 9, card: '9', naipe: 'copas', icon: 'cards-heart', image: '../assets/copas-9.jpg', title: 'Sua regra', rule: 'Você cria uma regra e quem descumprir bebe.' },
    { id: 10, card: '10', naipe: 'copas', icon: 'cards-heart', image: '../assets/copas-10.jpg', title: 'Categoria', rule: 'Ecolha uma categoria e o primeiro a errar ou não saber bebe.' },
    { id: 11, card: 'J', naipe: 'copas', icon: 'cards-heart', image: '../assets/copas-j.jpg', title: 'Frase', rule: 'Cada jogador fala uma palavra e o primeiro a errar bebe.' },
    { id: 12, card: 'Q', naipe: 'copas', icon: 'cards-heart', image: '../assets/copas-q.jpg', title: 'Rima', rule: 'Você fala uma palavra e o próximo tem que falar uma outra que rime com a sua.' },
    { id: 13, card: 'K', naipe: 'copas', icon: 'cards-heart', image: '../assets/copas-k.jpg', title: 'Rei', rule: 'Quando saírem todos os reis, o jogo acaba.' },
    
    { id: 14, card: 'A', naipe: 'ouros', icon: 'cards-diamond', image: '../assets/ouros-a.jpg', title: 'Todos bebem', rule: 'Começam ao mesmo tempo mas o da direita só pode parar de beber quando o da esquerda parar.' },
    { id: 15, card: '2', naipe: 'ouros', icon: 'cards-diamond', image: '../assets/ouros-2.jpg', title: 'Você bebe', rule: 'Beba 2 goles.' },
    { id: 16, card: '3', naipe: 'ouros', icon: 'cards-diamond', image: '../assets/ouros-3.jpg', title: 'Escolha quem vai beber', rule: 'Distribua 3 goles da forma que quiser.' },
    { id: 17, card: '4', naipe: 'ouros', icon: 'cards-diamond', image: '../assets/ouros-4.jpg', title: 'Mão na mesa', rule: 'O último a colocar a mão na mesa bebe.' },
    { id: 18, card: '5', naipe: 'ouros', icon: 'cards-diamond', image: '../assets/ouros-5.jpg', title: 'Mão pro alto', rule: 'O último a colocar a mão para o alto bebe.' },
    { id: 19, card: '6', naipe: 'ouros', icon: 'cards-diamond', image: '../assets/ouros-6.jpg', title: 'Homens bebem', rule: 'Todos os homens bebem.' },
    { id: 20, card: '7', naipe: 'ouros', icon: 'cards-diamond', image: '../assets/ouros-7.jpg', title: 'Mulheres bebem', rule: 'Todos as mulheres bebem.' },
    { id: 21, card: '8', naipe: 'ouros', icon: 'cards-diamond', image: '../assets/ouros-8.jpg', title: 'Na frente', rule: 'Quem está na sua frente bebe um gole.' },
    { id: 22, card: '9', naipe: 'ouros', icon: 'cards-diamond', image: '../assets/ouros-9.jpg', title: 'Sua regra', rule: 'Você cria uma regra e quem descumprir bebe.' },
    { id: 23, card: '10', naipe: 'ouros', icon: 'cards-diamond', image: '../assets/ouros-10.jpg', title: 'Categoria', rule: 'Ecolha uma categoria e o primeiro a errar ou não saber bebe.' },
    { id: 24, card: 'J', naipe: 'ouros', icon: 'cards-diamond', image: '../assets/ouros-j.jpg', title: 'Frase', rule: 'Cada jogador fala uma palavra e o primeiro a errar bebe.' },
    { id: 25, card: 'Q', naipe: 'ouros', icon: 'cards-diamond', image: '../assets/ouros-q.jpg', title: 'Rima', rule: 'Você fala uma palavra e o próximo tem que falar uma outra que rime com a sua.' },
    { id: 26, card: 'K', naipe: 'ouros', icon: 'cards-diamond', image: '../assets/ouros-k.jpg', title: 'Rei', rule: 'Quando saírem todos os reis, o jogo acaba.' },
    
    { id: 27, card: 'A', naipe: 'espadas', icon: 'cards-spade', image: '../assets/espadas-a.jpg', title: 'Todos bebem', rule: 'Começam ao mesmo tempo mas o da direita só pode parar de beber quando o da esquerda parar.' },
    { id: 28, card: '2', naipe: 'espadas', icon: 'cards-spade', image: '../assets/espadas-2.jpg', title: 'Você bebe', rule: 'Beba 2 goles.' },
    { id: 29, card: '3', naipe: 'espadas', icon: 'cards-spade', image: '../assets/espadas-3.jpg', title: 'Escolha quem vai beber', rule: 'Distribua 3 goles da forma que quiser.' },
    { id: 30, card: '4', naipe: 'espadas', icon: 'cards-spade', image: '../assets/espadas-4.jpg', title: 'Mão na mesa', rule: 'O último a colocar a mão na mesa bebe.' },
    { id: 31, card: '5', naipe: 'espadas', icon: 'cards-spade', image: '../assets/espadas-5.jpg', title: 'Mão pro alto', rule: 'O último a colocar a mão para o alto bebe.' },
    { id: 32, card: '6', naipe: 'espadas', icon: 'cards-spade', image: '../assets/espadas-6.jpg', title: 'Homens bebem', rule: 'Todos os homens bebem.' },
    { id: 33, card: '7', naipe: 'espadas', icon: 'cards-spade', image: '../assets/espadas-7.jpg', title: 'Mulheres bebem', rule: 'Todos as mulheres bebem.' },
    { id: 34, card: '8', naipe: 'espadas', icon: 'cards-spade', image: '../assets/espadas-8.jpg', title: 'Na frente', rule: 'Quem está na sua frente bebe um gole.' },
    { id: 35, card: '9', naipe: 'espadas', icon: 'cards-spade', image: '../assets/espadas-9.jpg', title: 'Sua regra', rule: 'Você cria uma regra e quem descumprir bebe.' },
    { id: 36, card: '10', naipe: 'espadas', icon: 'cards-spade', image: '../assets/espadas-10.jpg', title: 'Categoria', rule: 'Ecolha uma categoria e o primeiro a errar ou não saber bebe.' },
    { id: 37, card: 'J', naipe: 'espadas', icon: 'cards-spade', image: '../assets/espadas-j.jpg', title: 'Frase', rule: 'Cada jogador fala uma palavra e o primeiro a errar bebe.' },
    { id: 38, card: 'Q', naipe: 'espadas', icon: 'cards-spade', image: '../assets/espadas-q.jpg', title: 'Rima', rule: 'Você fala uma palavra e o próximo tem que falar uma outra que rime com a sua.' },
    { id: 39, card: 'K', naipe: 'espadas', icon: 'cards-spade', image: '../assets/espadas-k.jpg', title: 'Rei', rule: 'Quando saírem todos os reis, o jogo acaba.' },
    
    { id: 40, card: 'A', naipe: 'paus', icon: 'cards-club', image: '../assets/paus-a.jpg', title: 'Todos bebem', rule: 'Começam ao mesmo tempo mas o da direita só pode parar de beber quando o da esquerda parar.' },
    { id: 41, card: '2', naipe: 'paus', icon: 'cards-club', image: '../assets/paus-2.jpg', title: 'Você bebe', rule: 'Beba 2 goles.' },
    { id: 42, card: '3', naipe: 'paus', icon: 'cards-club', image: '../assets/paus-3.jpg', title: 'Escolha quem vai beber', rule: 'Distribua 3 goles da forma que quiser.' },
    { id: 43, card: '4', naipe: 'paus', icon: 'cards-club', image: '../assets/paus-4.jpg', title: 'Mão na mesa', rule: 'O último a colocar a mão na mesa bebe.' },
    { id: 44, card: '5', naipe: 'paus', icon: 'cards-club', image: '../assets/paus-5.jpg', title: 'Mão pro alto', rule: 'O último a colocar a mão para o alto bebe.' },
    { id: 45, card: '6', naipe: 'paus', icon: 'cards-club', image: '../assets/paus-6.jpg', title: 'Homens bebem', rule: 'Todos os homens bebem.' },
    { id: 46, card: '7', naipe: 'paus', icon: 'cards-club', image: '../assets/paus-7.jpg', title: 'Mulheres bebem', rule: 'Todos as mulheres bebem.' },
    { id: 47, card: '8', naipe: 'paus', icon: 'cards-club', image: '../assets/paus-8.jpg', title: 'Na frente', rule: 'Quem está na sua frente bebe um gole.' },
    { id: 48, card: '9', naipe: 'paus', icon: 'cards-club', image: '../assets/paus-9.jpg', title: 'Sua regra', rule: 'Você cria uma regra e quem descumprir bebe.' },
    { id: 49, card: '10', naipe: 'paus', icon: 'cards-club', image: '../assets/paus-10.jpg', title: 'Categoria', rule: 'Ecolha uma categoria e o primeiro a errar ou não saber bebe.' },
    { id: 50, card: 'J', naipe: 'paus', icon: 'cards-club', image: '../assets/paus-j.jpg', title: 'Frase', rule: 'Cada jogador fala uma palavra e o primeiro a errar bebe.' },
    { id: 51, card: 'Q', naipe: 'paus', icon: 'cards-club', image: '../assets/paus-q.jpg', title: 'Rima', rule: 'Você fala uma palavra e o próximo tem que falar uma outra que rime com a sua.' },
    { id: 52, card: 'K', naipe: 'paus', icon: 'cards-club', image: '../assets/paus-k.jpg', title: 'Rei', rule: 'Quando saírem todos os reis, o jogo acaba.' },
];
